[project]
name = "1-local-setup"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.9"
dependencies = [
    "dbt-core>=1.10.4",
    "dbt-postgres>=1.9.0",
    "dotenv>=0.9.9",
    "numpy>=2.3.1",
    "pandas>=2.3.1",
    "requests>=2.32.4",
]
